#  ************ 【系统设置】 ************* 
#  渲染精细度，可选值50~200，建议100。设置高精度会提高图片的精细度，但因图片较大可能会影响渲染与发送速度
renderScale: 100

#  渲染质量 可选值50~100
randerQuality: 100

#  渲染大小 可选任意值
b19size: 50

#  ************ 【发送设置】 ************* 
#  文字版b19是否带图，关闭可以节约大量发送时间
WordB19Img: true

#  文字版suggest是否带图，关闭可以节约大量发送时间
WordSuggImg: true